image:
  file: .gitpod.Dockerfile
tasks:
  - command: echo 'export PATH="$PATH":"$HOME/.pub-cache/bin"' >>~/.profile
  - command: dart pub global activate webdev
vscode:
  extensions:
    - Dart-Code.dart-code