tasks:
  - command: sudo apt-get update
  - command: sudo apt-get install apt-transport-https
  - command: wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
  - command: echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
  - command: sudo apt-get update
  - command: sudo apt-get install dart
  - command: echo 'export PATH="$PATH":"$HOME/.pub-cache/bin"' >>~/.profile
  - command: dart pub global activate webdev
vscode:
  extensions:
    - Dart-Code.dart-code