name: quickstart
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-29.0.dev <3.0.0'

# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
dependencies: 
  convert: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0